### ISSUE TITLE
[FeatureRequest] Tool types can be named anything

### ISSUE THREAD

**Issue by vezdeneszter** [axem-solutions/dem#109]
Currently, when the user creates a new Dev Env, they can only select from the “supported” tool types. The DEM doesn’t accept any Dev Env descriptor that is not included in the supported tool type list. 

This behavior should be changed because it limits the usability for no reason.

The DEM should not check whether the tool type is supported or not. Any name can be given for a tool type.

The “supported” tool types are stored in the DevEnv class’s supported_tool_types class variable.

**Comment by officialasishkumar** [comment]
Hi @vezdeneszter, 

Do you want me to just ask for the name of the tool type?

**Comment by janosmurai** [comment]
No, the only task is to remove the _check_tool_type_support() method from the DevEnv class. 
(The supported_tool_types class variable is still needed for the TUI, so don't delete that one.)

Please tell us if you'd like to start working on an issue, so we can assign it to you! Thanks!

**Comment by amathestar** [comment]
Hi @janosmurai, is this task still open? I would like to work on it

**Comment by janosmurai** [comment]
Hello @amathestar 
Yes, it is still open. I'll assign it to you.

**Comment by amathestar** [comment]
Hi @janosmurai, seem to be struggling with the pytest after removing the  _check_tool_type_support() method. Can I get some assistance?

**Comment by janosmurai** [comment]
Hey @amathestar 
Sure thing, let's discuss it on Discord!

**Comment by janosmurai** [comment]
Hey @amathestar 
Are you still working on this issue? Tell me if you need any help!
