### ISSUE TITLE
[BUG] - v0.2.0 - Check parameter handling of the commands

### ISSUE THREAD

**Issue by vezdeneszter** [axem-solutions/dem#111]
**Describe the bug**
If there is any additional parameter, the DEM raises an error, except if the --help option is used.

**To Reproduce**
Currently, if I try to execute 

`dem list --help asd
`
dem ignores the extra asd parameter and gives back the expected result of the

`dem list --help
`
but if I try to execute 

`dem list --all --env asd
`
I get back an error message highlighting there is an unexpected argument.

### Expected behavior
The DEM should raise an error if any additional parameter has been added with the --help option.

Test all the commands with the --help option.

**Comment by Preetraj2002** [comment]
hey @vezdeneszter i a beginner in open-source and have only contributed to super easy issues. I am genuinely interested in this repo as I always wanted to learn about dockers and containerization. This seems to be the perfect opportunity for me. Please help me give started with this task, it would be really helpful if you could provide some resources.

**Comment by vezdeneszter** [comment]
Hi @Preetraj2002 , thanks for checking DEM!

Some of our issues have the label "good first issue", as you are a beginner I would recommend checking those first and starting with them instead of this one.

I also recommend joining our Discord channel where the communication is more effective: https://discord.com/invite/2a67N75P
