### ISSUE TITLE
[BUG] - v0.2.0 - Whitespace in Dev Env name is not acceptable.

### ISSUE THREAD

**Issue by vezdeneszter** [axem-solutions/dem#113]
**Describe the bug**
The DEM should not accept any whitespace in the name of a Dev Env.

**To Reproduce**

1. Create a new Dev Env with the name “ “
 `dem create " "`
2. Set the parameters for the new Dev Env.
3. The Dev Env gets created with the name “ “.

### Expected behavior
The DEM should notify the user that the name of the Dev Env can’t contain any spaces.

**Comment by chriscarnold** [comment]
Hi @vezdeneszter, can this be assigned to me? would love to work on this!
