### ISSUE TITLE
[DOC] Update Readme

### ISSUE THREAD

**Issue by ayushmankoley** [axem-solutions/dem#118]
**Is your Documentation request related to a problem? Please describe.**
A user always frustrated when trying to find specific parts of readme

**Describe the solution you'd like**
A Table of content

**Additional context**
Add Table of Content and Contributors to Readme

would love to work, please assign

**Comment by vezdeneszter** [comment]
Hey, 

thanks for checking our project!

The contributors are already displayed on the right panel and we would like to avoid duplication if it is not necessary. 
Also when starting with DEM, we prefer developers to read the whole readme as it is quite short and contains minimal but necessary information for first steps. 
In the detailed documentation of DEM (linked in readme), we have a Table of Contents for the exact reason you mentioned.

Please, when creating your next issue follow our contributing guideline: https://github.com/axem-solutions/.github/blob/4bdc1be72b0a2c97da19408c59d6dd5d1845a469/CONTRIBUTING.md
