### ISSUE TITLE
[FeatureRequest] Modify the existing delete command - delete the Dev Env descriptor from the dev_env.json file

### ISSUE THREAD

**Issue by vezdeneszter** [axem-solutions/dem#122]
`dem delete DEV_ENV_NAME
`

**Deletes the Dev Env descriptor from the dev_env.json and removes all required unused tools images.**

1. The DEM looks for the DEV_ENV_NAME.
- If it can’t find the Dev Env, an error should be raised and the execution should be aborted.
2. The DEM runs the uninstall for the Dev Env. It removes all the tool images, which are not required anymore by any other Dev Env.
3. The DEM finally removes the Dev Env descriptor from the dev_env.json file.
4. If the DEV_ENV_NAME is an empty parameter, the DEM should raise an error. (Handled by type)
5. The DEM should autocomplete the DEV_ENV_NAME parameter with the locally available Dev Envs.

![image-20231003-101549](https://github.com/axem-solutions/dem/assets/13817488/d542039b-028c-40bf-814d-f666fdf7073c)

**Comment by VibhorGits** [comment]
Hey @vezdeneszter Can I work on this issue?
If yes may I ask you to elaborate a little on the problem.

**Comment by janosmurai** [comment]
Hey @VibhorGits
Sure you can.
Please join our [discord](https://discord.com/invite/Nv6hSzXruK) and I happily elaborate on this issue.
