### ISSUE TITLE
[FeatureRequest] Delete host command

### ISSUE THREAD

**Issue by vezdeneszter** [axem-solutions/dem#124]
`dem del-host NAME`

Deletes the host from the config file.

If the NAME is an empty string, the DEM should raise an error. (Handled by typer).

If the DEM can’t find the NAME in the list of the available hosts, it should raise an error and abort.

The DEM should autocomplete the NAME with the already available host names from the config file.

![image-20231003-110214](https://github.com/axem-solutions/dem/assets/13817488/223eef2f-2217-42ab-85f9-0b589882b3db)

**Comment by Zhreyu** [comment]
hey I would like to work on this issue :)

**Comment by janosmurai** [comment]
Hey @Zhreyu 
Are you still working on this issue?
Tell me if you need any help!
