### ISSUE TITLE
[FeatureRequest] Modify command - add option to modify the host for the tool images

### ISSUE THREAD

**Issue by janosmurai** [axem-solutions/dem#133]
:warning: Unsolved dependency: the Dev Env settings panel must be implemented first!

In the Dev Env settings panel, if the user selects the host, its value gets saved to the dev_env.json.

**Comment by Ayush-gupta-dev** [comment]
I have gone through your readme.md file, and i would like to contribute in this repository, please assign this issue to me @janosmurai.

**Comment by janosmurai** [comment]
Hello @Ayush-gupta-dev 
We're happy that you're interested in this repository! Unfortunately, this issue has an unsolved dependency, which I haven't noted yet in the description. Could you select another one? If you join our [Discord channel](https://discord.com/invite/Nv6hSzXruK), we can help you find an interesting issue!

**Comment by janosmurai** [comment]
Design change:

Instead of assigning the tool images to hosts, the user can set which host should run a given task. This can be set on the Task Settings tab of the Dev Env Settings window. See https://github.com/axem-solutions/dem/issues/213 for more info.
