### ISSUE TITLE
[FeatureRequest] Install command - install a Dev Env from a locally available Dev Env descriptor

### ISSUE THREAD

**Issue by janosmurai** [axem-solutions/dem#134]
dem install DEV_ENV_NAME

1. The DEM looks for the DEV_ENV_NAME in the local dev_env.json.
If the DEM can’t find the Dev Env, it should report an error for the user and stop the execution.
2. The DEM pulls the images one-by-one from the registries to the local host machine.
3. The DEM should inform the user about the successful operation if all the images are pulled.
4. In the Dev Env descriptor set the “installed” key to “True”.
`"installed": "True",`
5. If the DEV_ENV_NAME is an empty parameter, the DEM shall raise an error. (Handled by typer.)
6. The DEM should autocomplete the DEV_ENV_NAME with the locally already available Dev Envs.

![image](https://github.com/axem-solutions/dem/assets/11297633/240b153d-125d-424d-9873-a3d98c63833b)

**Comment by Celsuss** [comment]
I can take a look at this issue.

**Comment by janosmurai** [comment]
Great, I'll assign it to you!
#110 blocks the implementation of the autocomplete (6th point in the issue description), so you can ignore that one. 
If you have any questions, feel free to ask them on our [Discord](https://discord.com/invite/Nv6hSzXruK).

**Comment by Celsuss** [comment]
> Great, I'll assign it to you! #110 blocks the implementation of the autocomplete (6th point in the issue description), so you can ignore that one. If you have any questions, feel free to ask them on our [Discord](https://discord.com/invite/Nv6hSzXruK).

Great thanks for telling me!

**Comment by janosmurai** [comment]
Hey @Celsuss 
Are you still working on this issue? 
Tell me if you need any help!
