### ISSUE TITLE
[FeatureRequest] Improved developer environment using CI/CD-based automation workflows

### ISSUE THREAD

**Issue by hitblast** [axem-solutions/dem#221]
**Is your feature request related to a problem? Please describe.**

It's not necessarily a problem, but a rather "inconvenience" while settings things up as a developer. While I found DEM to be a very interesting project, working as an open-source contributor had sparked a few things in my mind. Although the user side of things are pretty handy, I feel like as a developer who has worked on building several Python packages in his life, automation is a key part.

**Describe the solution you'd like**

I'd like to deploy several CI/CD workflows dedicated to making the process of deploying later versions of DEM easier. Later on, I'll focus on contributing to the internal structure of the CLI for making it easier to be worked on.

**Describe alternatives you've considered**

No alternatives, as of now, except manually letting developers do each of these which I don't think is a good solution.

**Additional context**

That's it :)

**Comment by janosmurai** [comment]
Adding automation to get rid of repetitive tasks is always a good idea! Thanks @hitblast!

Just to be clear, in the context of this issue, you'd like to add a new workflow that makes the PyPI package deployment automatic after creating a new release here on GitHub. 

Please create separate issues for your future ideas!

**Comment by hitblast** [comment]
> Adding automation to get rid of repetitive tasks is always a good idea! Thanks @hitblast!
> 
> Just to be clear, in the context of this issue, you'd like to add a new workflow that makes the PyPI package deployment automatic after creating a new release here on GitHub.
> 
> Please create separate issues for your future ideas!

Sure thing! I hope it'll come to good use for the project later on.
